# coding:utf-8
"""
Django settings for queuesystem project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k#g5_5ahevdx!jepi!46zmvdjo1l+kwyg0-@76e%13k^f%ht7c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


if 'SERVER_SOFTWARE' in os.environ:
    from sae.const import (
        MYSQL_HOST, MYSQL_PORT, MYSQL_USER, MYSQL_PASS, MYSQL_DB
    )

    # 新浪云的本地文件系统是只读的，修改 django 的 file storage backend 为 Storage
    DEFAULT_FILE_STORAGE = 'sae.ext.django.storage.backend.Storage'
    # 使用 media 这个 bucket
    STORAGE_BUCKET_NAME = 'media'
    # ref: https://docs.djangoproject.com/en/dev/topics/files/
else:
    local = True
    if not local:
        # Make `python manage.py syncdb` works happy!
        from sae._restful_mysql import monkey
        monkey.patch()
        MYSQL_HOST = 'w.rdc.sae.sina.com.cn'
        MYSQL_PORT = '3307'
        MYSQL_USER = '253wky0j0n'
        MYSQL_PASS = 'im44lmx5y3y04zmlxzxml0wz211j5wx3l1kj3xlj'
        MYSQL_DB = 'app_queuesystem'
    else:
        MYSQL_HOST = '127.0.0.1'
        MYSQL_PORT = '3306'
        MYSQL_USER = 'root'
        MYSQL_PASS = '123456'
        MYSQL_DB = 'test'

        MEDIA_URL = '/media/'
        MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'queue',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'queuesystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'queuesystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MYSQL_DB,
        'USER': MYSQL_USER,
        'PASSWORD': MYSQL_PASS,
        'HOST': MYSQL_HOST,
        'PORT': MYSQL_PORT,
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False #timezone 时间与datetime一致 (timezone y永远是UTC时间)

LOGIN_URL = "/queue/login"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/


SITE_ROOT = os.path.join(os.path.abspath(os.path.dirname(__file__)),'')
STATIC_ROOT = os.path.join(SITE_ROOT,'static')
STATIC_URL = '/static/'


STATIC_PATH = os.path.join(BASE_DIR,'media')

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# 修改上传时文件在内存中可以存放的最大 size 为 10m
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760



